# Generated by Django 3.2.13 on 2022-06-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Team',
        ),
    ]
